# Generated by Django 5.1.6 on 2025-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soft', '0002_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
